config/routes.rb
Rails.application.routes.draw do
  
  get 'properties/index'
  get 'properties/show'
  get 'properties/buy'
  
  resources :properties
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  
  get 'users/new'
  get 'pages/index'
  root 'pages#index'
  
  resources :users
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  get 'favorites/index'
  post '/favorites', to: 'favorites#create'

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :property
end

app/models/property.rb
class Property < ApplicationRecord
    mount_uploader :image, ImageUploader
    enum utilityfrom:{
    Rent:1,
    Buy:2
    }
    
    has_many :favorites
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  
  has_secure_password
  
 
  has_many :favorites
  has_many :favorite_properties, through: :favorites, source: 'property'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  add_flash_types :success, :info, :warning, :danger
  
  helper_method :current_user, :logged_in?
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorite_properties = current_user.favorite_properties
  end

  def create
    favorite = Favorite.new
    favorite.user_id = current_user.id
    favorite.property_id = params[:property_id]

    if favorite.save
      redirect_to properties_path, success: 'お気に入りに登録しました'
    else
      redirect_to properties_path, danger: 'お気に入りに登録に失敗しました'
    end
  end
  
  def destroy
    favorite = Favorite.find_by(user_id: current_user.id, property_id: params[:property_id])
    favorite.destroy if favorite.present?
    if favorite.destroyed?
      redirect_to properties_path, success: 'お気に入りを解除しました'
    else
      redirect_to properties_path, danger: 'お気に入り解除に失敗しました'
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  def index
    @properties = Property.where(utilityfrom: 1)
  end

  def buy
    @properties = Property.where(utilityfrom: 2)
  end
  
  def show
  end
end

app/controllers/property_controller.rb
class PropertyController < ApplicationController
  def index
    @properties = Property.where(utilityfrom: 1)
  end

  def buy
    @properties = Property.where(utilityfrom: 2)
  end
  
  def show
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to root_path, success: 'ログインに成功しました'
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    log_out
    redirect_to root_url, info: 'ログアウトしました'
  end

  private
  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  
  def create
    @user = User.new(user_params)
    # binding.pry
    if @user.save
      redirect_to root_path, success: '登録が完了しました'
    else
      flash.now[:danger] = "登録に失敗しました"
      render :new
    end
  end

 private
def user_params
  params.require(:user).permit(:name, :email, :password, :password_confirmation)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/property_helper.rb
module PropertyHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/index.html.erb
<div class="property-index-wrapper">
  <div class="container">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="property-index-single">
            <h2>物件情報/Rent</h2>
               <% @favorite_properties.each do|property|%>
                  <p>〇<%= property.title%></p>
                     <p><%= property.description %></p>
                      
                     <% if property.image.present? %>
                          <p>
                              <%= image_tag property.image.url, class: 'image' %>
                          </p>
                     <% end %>
               <% end%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
    <% end %>
      <nav class="navbar navbar-default navbar-fixed-top navbar-transparent">
        <div class="container">
          <%= link_to root_path do %>
            <span><%= image_tag "N-house.jpg", class: "navbar-brand" %></span>
          <% end %>
          <ul class="nav navbar-nav navbar-right">
            <% if logged_in? %>
            <li>
              <%= link_to favorites_index_path do %>
                <%= image_tag "icons/heart.png" %>
              <% end %>
            </li>
            <li>
              <%= link_to logout_path, method: :delete do %>
                <%= image_tag "icons/logout.png" %>
              <% end %>
            </li>
          <% else %>
            <li>
              <%= link_to new_user_path do %>
                <%= image_tag "icons/register.png" %>
              <% end %>
            </li>
            <li>
              <%= link_to login_path do %>
                <%= image_tag "icons/login.png" %>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    
    <%= yield %>
    
  <script>
  $(function(){
    $(".alert").fadeOut(5000);
  });
  </script>

 
  </body>
</html>

app/views/pages/index.html.erb
<div class="top-hero-wrapper text-center">
  <div class="container top-hero-container">
    <h1 class="text-white">良い住み方から素晴らしい町へ</h1>
    <h2 class="text-white">From a good way of living to a good town.</h2>
    <h3>
        <div class="col-md-offset-1 col-md-5">
          <%= link_to properties_index_path do %>
            <%= image_tag 'Rent pqh8miee.png', size: '400x200', class: 'hoge' %>
          <% end %>
        </div>
        <div class="col-md-4">
          <%= link_to properties_buy_path do %>
            <%= image_tag 'Buy pqh8miee.png', size: '400x200', class: 'hoge' %>
          <% end %>
        </div>
    </h3>
  </div>
</div>

app/views/properties/buy.html.erb
<div class="topic-index-wrapper">
  <div class="container">
      <div class="row">
        <div class="col-md-10 col-md-offset-2">
          <div class="topic-index-single">
            <h2>物件情報/buy</h2>
               <% @properties.each do|property|%>
                    <p>..................................................................................................................................................</p>
                      <p>◎◎<%= property.title%></p>
                         <p><%= property.description %></p>
                          
                         <% if property.image.present? %>
                              <p>
                                  <%= image_tag property.image.url, class: 'image' %>
                              </p>
                         <% end%>
                         <% if logged_in? %>
                            <div>
                             <%= link_to favorites_path(property_id: property.id), method: :post do %>
                                <%= image_tag 'icons/heart-black.png', class: 'topic-index-icon' %>
                             <% end %>
                            </div>
                         <% end %>
            　　<% end%>
         </div>
       </div>
     </div>
   </div>
 </div>

app/views/properties/index.html.erb
<div class="topic-index-wrapper">
  <div class="container">
      <div class="row">
        <div class="col-md-10 col-md-offset-2">
          <div class="topic-index-single">
            <h2>物件情報/Rent</h2>
               <% @properties.each do|property|%>
                    <p>..................................................................................................................................................</p>
                      <p>◎◎<%= property.title%></p>
                         <p><%= property.description %></p>
                          
                         <% if property.image.present? %>
                              <p>
                                  <%= image_tag property.image.url, class: 'image' %>
                              </p>
                         <% end%>
                         <% if logged_in? %>
                            <div>
                             <%= link_to favorites_path(property_id: property.id), method: :post do %>
                                <%= image_tag 'icons/heart-black.png', class: 'topic-index-icon' %>
                             <% end %>
                            </div>
                         <% end %>
            　　<% end%>
         </div>
       </div>
     </div>
   </div>
 </div>

app/views/properties/show.html.erb
<h1>Property#show</h1>
<p>Find me in app/views/property/show.html.erb</p>

app/views/users/new.html.erb
<div class="users-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 users-new-container">
        <h1 class="text-center text-white">会員登録</h1>
        <%= form_for @user do |f| %>
          <div class="form-group">
            <%= f.label :name, class: 'text-white' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :email, class: 'text-white' %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password, class: 'text-white' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password_confirmation, class: 'text-white' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>

          <%= f.submit "登録", class: 'btn-block user-white2' %>
        <% end %>
        <%= link_to 'ログインはこちら', '#',class: 'text-white' %>
      </div>
    </div>
  </div>
</div>